'use strict';

const fields = {
  Id: Number,
  Number: { type: Number, unique: true, required: true },
  CustomerId: Number,
  CustomerName: String,
  CustomerCode: String,
  CustomerKey: String,
  CustomerReference: String,
  CustomerContactName: String,
  CustomerContactFirstName: String,
  CustomerContactLastName: String,
  CreatedDate: Date,
  Currency: {},
  NetAmount: Number,
  GrossAmount: Number,
  VATAmount: Number,
  HomeCurrencyGrossAmount: Number,
  HomeCurrencyVATAmount: Number,
  AmountPaid: Number,
  TotalPaidAmount: Number,
  Paid: Number,
  DueAmount: Number,
  FormattedDueAmount: String,
  IssuedDate: Date,
  DueDate: Date,
  PaidDate: Date,
  LastPaymentDate: Date,
  Status: String,
  Type: String,
  LineItems: [{}],
  PaymentLines: [{}],
  Address: {},
  DeliveryAddress: {},
  UseCustomDeliveryAddress: Boolean,
  Permalink: String,
  PackingSlipPermalink: String,
  ReminderLetters: [{}],
  PreviousNumber: Number,
  NextNumber: Number,
  OverdueDays: Number,
  EmailCount: Number,
  FileCount: Number,
  AutomaticCreditControlEnabled: Boolean,
  CustomerDiscount: Number,
  InvoiceInECMemberState: Boolean,
  InvoiceOutsideECMemberState: Boolean,
  IsArchived: Boolean,
  IsCISReverseCharge: Boolean,
  IsWhtDeductionToBeApplied: Boolean,
  CISRCNetAmount: Number,
  CISRCVatAmount: Number,
  PayOnlinePaymentProcessor: Number,
  ProjectNumber: Number,
  ProjectName: String,
  ProjectGrossAmount: Number,
  SuppressNumber: Number,
  TradeBorderType: String,
  UpdateCustomerAddress: Boolean,
  UpdateCustomerDeliveryAddress: Boolean,
  VATNumber: String,
  VATReturnId: Number,
};

const indexes = [
  { fields: { Id: 1 }, options: { unique: true, sparse: true } },
];

module.exports = { collection: 'invoices', fields, indexes };
