'use strict';

const paymentLineFields = {
  BulkPaymentNumber: Number,
  Permalink: String,
  PaymentProcessorEnumValue: Number,
  IsPaymentCreditNote: Boolean,
  VATReturnId: Number,
  Id: Number,
  Date: Date,
  BulkId: Number,
  BFSTransactionId: {},
  PaymentProcessor: Number,
  AccountId: Number,
  Note: String,
  Method: Number,
  Amount: Number,
  PayDate: Date,
};

const fields = {
  Id: Number,
  Number: { type: Number, unique: true, required: true },
  SupplierId: Number,
  SupplierCode: String,
  SupplierName: String,
  SupplierReference: String,
  Currency: {},
  DueDate: Date,
  GrossAmount: Number,
  HomeCurrencyGrossAmount: Number,
  IssuedDate: Date,
  FileCount: Number,
  LineItems: [{}],
  NetAmount: Number,
  NextNumber: Number,
  OverdueDays: Number,
  PaidDate: Date,
  // PaymentLines handled separately via paymentLineFields (needs sub-schema wrapping)
  Permalink: String,
  PreviousNumber: Number,
  PurchaseInECMemberState: Boolean,
  ProjectGrossAmount: Number,
  ProjectNumber: Number,
  ProjectName: String,
  Status: String,
  StockManagementApplicable: Boolean,
  TotalPaidAmount: Number,
  TradeBorderType: String,
  Type: String,
  VATAmount: Number,
  VATReturnId: Number,
  AdditionalFieldValue: String,
  CISRCNetAmount: Number,
  CISRCVatAmount: Number,
  DueAmount: Number,
  IsCISReverseCharge: Boolean,
  IsEmailSent: Boolean,
  IsWhtDeductionToBeApplied: Boolean,
  ReadableString: String,
  SubmissionDate: Date,
  TaxMonth: Number,
  TaxYear: Number,
};

const indexes = [
  { fields: { Id: 1 }, options: { unique: true, sparse: true } },
];

module.exports = { collection: 'purchases', fields, paymentLineFields, indexes };
